services:
  node:
    container_name: mern-node
    build: .
    volumes:
      - .:/app
    ports:
      - "${API_PORT:-8080}:${API_PORT:-8080}"
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    networks:
      - mern
  mongodb:
    container_name: mern-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - mern

volumes:
  mongo_data:

networks:
  mern:
